# Exercicio 19

In [7]:
import pandas as pd

df_pinguim = pd.read_csv("palmerpenguins_extended.csv")
df_pinguim

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,diet,life_stage,health_metrics,year
0,Adelie,Biscoe,53.4,17.8,219.0,5687.0,female,fish,adult,overweight,2021
1,Adelie,Biscoe,49.3,18.1,245.0,6811.0,female,fish,adult,overweight,2021
2,Adelie,Biscoe,55.7,16.6,226.0,5388.0,female,fish,adult,overweight,2021
3,Adelie,Biscoe,38.0,15.6,221.0,6262.0,female,fish,adult,overweight,2021
4,Adelie,Biscoe,60.7,17.9,177.0,4811.0,female,fish,juvenile,overweight,2021
...,...,...,...,...,...,...,...,...,...,...,...
3425,Gentoo,Biscoe,44.0,20.4,252.0,6447.0,male,squid,adult,healthy,2025
3426,Gentoo,Biscoe,54.5,25.2,245.0,6872.0,male,squid,adult,healthy,2025
3427,Gentoo,Biscoe,51.4,20.4,258.0,7409.0,male,squid,adult,overweight,2025
3428,Gentoo,Biscoe,55.9,20.5,247.0,6491.0,male,squid,adult,healthy,2025
3429,Gentoo,Biscoe,43.9,22.9,206.0,6835.0,male,squid,adult,healthy,2025

In [18]:
test = df_pinguim['species'].unique()

specie_1 = df_pinguim[df_pinguim['species'] == test[0]]
specie_2 = df_pinguim[df_pinguim['species'] == test[1]]
specie_3 = df_pinguim[df_pinguim['species'] == test[2]]

media_peso_1 = specie_1['body_mass_g'].mean() # media de peso especie 1
media_asa_1 = specie_1['flipper_length_mm'].mean() # media da asa especie 1
media_bico_1 = specie_1['bill_length_mm'].mean() # media comprimento do bico especie 1

media_peso_2 = specie_2['body_mass_g'].mean() # media de peso especie 2
media_asa_2 = specie_2['flipper_length_mm'].mean() # media da asa especie 2
media_bico_2 = specie_2['bill_length_mm'].mean() # media comprimento do bico especie 2

media_peso_3 = specie_3['body_mass_g'].mean() # media de peso especie 3
media_asa_3 = specie_3['flipper_length_mm'].mean() # media da asa especie 3
media_bico_3 = specie_3['bill_length_mm'].mean() # media comprimento do bico especie 3

SyntaxError: invalid decimal literal (1905929458.py, line 9)

### Existem valores ausentes ou inconsistentes no dataset? Se sim, como vocÃª trataria esses dados para garantir a qualidade da anÃ¡lise?

In [ ]:
df_pinguim.isnull().sum()

### Realize uma anÃ¡lise exploratÃ³ria dos dados para entender as caracterÃ­sticas fÃ­sicas (como peso, comprimento do bico e comprimento da asa) das trÃªs espÃ©cies de pinguins. Utilize agregaÃ§Ãµes e agrupamentos para comparar essas caracterÃ­sticas entre as espÃ©cies.

In [5]:
caract = df_pinguim[['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']]
caract.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm   body_mass_g
count     3430.000000    3430.000000        3430.000000   3430.000000
mean        38.529825      18.447143         207.028863   4834.710496
std         13.175171       2.774428          28.944765   1311.091310
min         13.600000       9.100000         140.000000   2477.000000
25%         28.900000      16.600000         185.000000   3843.500000
50%         34.500000      18.400000         203.000000   4633.500000
75%         46.600000      20.300000         226.000000   5622.000000
max         88.200000      27.900000         308.000000  10549.000000

### Crie grÃ¡ficos para visualizar as diferenÃ§as entre as espÃ©cies de pinguins com base nas caracterÃ­sticas fÃ­sicas. Use grÃ¡ficos de dispersÃ£o, boxplot e histogramas para mostrar as distribuiÃ§Ãµes e comparaÃ§Ãµes entre as variÃ¡veis.